import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
try {const p=await b.newPage();await p.setViewport({width:1440,height:900});await p.goto(process.env.QA_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle0'});await p.waitForSelector('.verse.active');const nums=()=>p.$$eval('.verse sup',es=>es.map(e=>e.textContent));
await p.keyboard.press('d');assert.deepEqual(await nums(),['2']);await p.keyboard.press('a');assert.deepEqual(await nums(),['1']);await p.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{key:'d',repeat:true})));await p.keyboard.down('Control');await p.keyboard.press('d');await p.keyboard.up('Control');assert.deepEqual(await nums(),['1']);await p.screenshot({path:'qa/keyboard-tip.png'});await p.click('[aria-label="Dismiss keyboard tip"]');await p.reload({waitUntil:'networkidle0'});assert.equal(await p.$('.shortcut-coach'),null);
await p.click('.setup-button');await p.click('[aria-label="Verses in view"] button:nth-child(2)');await p.click('[aria-label="Close settings"]');assert.deepEqual(await nums(),['1','2']);await p.click('.writing-mode-button');assert.equal(await p.$eval('.companion',e=>getComputedStyle(e).visibility),'visible');assert.equal(await p.$eval('.companion p',e=>getComputedStyle(e).fontSize),await p.$eval('.active p',e=>getComputedStyle(e).fontSize));await p.keyboard.press('d');assert.deepEqual(await nums(),['3','4']);await p.keyboard.press('a');assert.deepEqual(await nums(),['1','2']);await p.screenshot({path:'qa/two-verses.png'});
const go=async ref=>{await p.click('.reference-picker');await new Promise(r=>setTimeout(r,100));await p.type('[name="reference"]',ref);await p.keyboard.press('Enter');await p.waitForFunction(()=>!document.querySelector('[role="dialog"]'))}
await go('Genesis 1:31');assert.deepEqual(await nums(),['31']);await p.keyboard.press('d');assert.deepEqual(await nums(),['1','2']);await p.keyboard.press('a');assert.deepEqual(await nums(),['31']);await go('Revelation 22:20');assert.deepEqual(await nums(),['20','21']);assert.ok(await p.$eval('.next-button',e=>e.disabled));await p.keyboard.press('d');assert.deepEqual(await nums(),['20','21']);await go('John 3:16');await p.setViewport({width:390,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.$eval('.companion',e=>e.scrollIntoView({block:'end'}));assert.ok(await p.$eval('.companion',e=>e.getBoundingClientRect().bottom<=innerHeight));await p.screenshot({path:'qa/two-verses-mobile.png'});await p.reload({waitUntil:'networkidle0'});await p.waitForSelector('.companion');assert.deepEqual(await nums(),['16','17']);await p.click('.reference-picker');await new Promise(r=>setTimeout(r,100));await p.type('[name="reference"]','Daniel 1:1');assert.deepEqual(await nums(),['16','17']);console.log('PASS: A/D, modifiers/repeat guards, hint dismissal persists, two-verse preference persists, pair stepping, odd chapter boundary, Bible end, focus visibility and equal type, mobile second verse reachable, typing protected.')
} finally{await b.close()}
