import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
try{
const p=await b.newPage(); const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setViewport({width:1440,height:900});await p.goto(process.env.QA_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle0'});await p.waitForSelector('.verse.active p');
const rect=()=>p.$eval('.verse.active p',e=>{let r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width}})
const num=()=>p.$eval('.verse.active sup',e=>e.textContent)
assert.equal(await p.$$eval('.verse',e=>e.length),1);assert.equal(await p.$('.topbar'),null);assert.equal(await p.$('[name="translation"]'),null);
await p.screenshot({path:'qa/handwriting-desktop.png'});const before=await rect();await p.click('.writing-mode-button');await p.waitForFunction(()=>!!document.fullscreenElement);assert.deepEqual(await rect(),before);await p.keyboard.press('Space');assert.equal(await num(),'2');assert.deepEqual(await rect(),before);await p.keyboard.press('ArrowLeft');assert.equal(await num(),'1');await p.keyboard.down('Control');await p.keyboard.press('ArrowRight');await p.keyboard.up('Control');assert.equal(await num(),'1');await p.screenshot({path:'qa/handwriting-focus.png'});
for(const hand of ['Left','Right']){
 await p.click('.setup-button');await p.waitForSelector('[aria-label="Writing hand"]');await p.evaluate(h=>[...document.querySelectorAll('[aria-label="Writing hand"] button')].find(e=>e.textContent===h).click(),hand);await p.click('[aria-label="Close settings"]');
 const target=await p.$eval('.next-button',e=>{let r=e.getBoundingClientRect();return {x:r.x,width:r.width,height:r.height}});assert.ok(target.height>=300&&target.width>=80);assert.equal(target.x>720,hand==='Left');await p.click('.next-button');await p.keyboard.press('Space');await p.keyboard.press('ArrowLeft');
}
await p.click('.setup-button');await p.click('.line-guide-button');await p.click('[aria-label="Close settings"]');await p.click('.guided-text');assert.ok(await p.$('.guided-text[data-line-marked]'));
await p.click('.reference-picker');await p.type('[name="reference"]','John 3:16');await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('.reference-picker').textContent.includes('3:16'));await p.click('.page-ribbon');
for(const t of ['BSB','ASV1901','WEB']){await p.click('.reference-picker');await p.select('[name="navigator-translation"]',t);await p.waitForFunction(t=>document.querySelector('.reference-picker')?.textContent.includes(t==='ASV1901'?'ASV':t),{},t);await new Promise(r=>setTimeout(r,250));assert.ok(await p.$('.focus-writing'));}
await p.click('.writing-mode-button');await p.waitForFunction(()=>!document.fullscreenElement);await p.setViewport({width:390,height:844});await p.screenshot({path:'qa/handwriting-mobile.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.click('.writing-mode-button');await p.click('.next-button');await p.screenshot({path:'qa/handwriting-mobile-focus.png'});await p.click('.writing-mode-button');await p.evaluate(()=>navigator.serviceWorker.ready);await p.setOfflineMode(true);await p.reload({waitUntil:'networkidle0'});await p.waitForSelector('.verse.active');assert.ok(await p.$eval('.landscape-scene img',e=>e.complete&&e.naturalWidth>0));assert.ok(await p.$eval('.reference-picker',e=>e.textContent.includes('3:17')));assert.deepEqual(errors,[]);console.log('PASS: one verse, no duplicate controls, fullscreen stable anchor, Space/arrows/modifier guards, both hand target placement and dimensions, line guide via settings, passage/three translations, bookmark, mobile layout, offline image and resume.');
}finally{await b.close()}
