import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
try {
const p=await b.newPage();await p.setViewport({width:1440,height:1000});await p.goto(process.env.QA_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle0'});await p.waitForSelector('.verse.active');const wait=()=>new Promise(r=>setTimeout(r,350));const open=async()=>{await p.click('.reference-picker');await wait()};const stored=()=>p.evaluate(()=>localStorage.getItem('scripture-scribe-library-v3'));const original=await stored();await open();await p.click('[aria-controls="chapters-GEN"]');assert.ok(await p.$('[aria-label="Genesis 1 · Your place"]'));await p.click('.testament-tabs button:nth-child(2)');await p.click('[aria-controls="chapters-JHN"]');assert.equal(await stored(),original);await p.click('[aria-label="John 3"]');await p.waitForFunction(()=>!document.querySelector('[role="dialog"]'));assert.match(await p.$eval('.reference-picker',e=>e.textContent),/John 3:1/);
await open();await p.click('.starting-points button');assert.match(await p.$eval('.reference-picker',e=>e.textContent),/Psalms 23:1/);await open();await p.select('[name="navigator-translation"]','DRA');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('DRA'));await open();assert.equal(await p.$$eval('.book-cover',es=>es.length),46);const names=await p.$$eval('.book-cover strong',es=>es.map(e=>e.textContent));await p.click('.testament-tabs button:nth-child(2)');names.push(...await p.$$eval('.book-cover strong',es=>es.map(e=>e.textContent)));assert.equal(new Set(names).size,73);await fs.mkdir('qa',{recursive:true});await fs.writeFile('qa/book-coverage.json',JSON.stringify(names,null,2));await p.click('.testament-tabs button:first-child');await p.click('[aria-controls="chapters-TOB"]');await p.click('[aria-label="Tobit 1"]');assert.match(await p.$eval('.reference-picker',e=>e.textContent),/Tobit 1:1/);await open();await p.click('.starting-points button');assert.match(await p.$eval('.reference-picker',e=>e.textContent),/Psalms 22:1/);await open();await p.click('[aria-controls="chapters-PSA"]');await wait();await p.screenshot({path:'qa/books-desktop.png'});
await p.setViewport({width:390,height:844});await p.$eval('.book-browser',e=>e.scrollIntoView({block:'start'}));await wait();await p.screenshot({path:'qa/books-mobile.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await p.$$eval('.chapter-grid button',es=>es.every(e=>e.getBoundingClientRect().height>=44)));await p.click('[aria-label="Close passage navigator"]');assert.ok(await p.$('.reader-random'));await p.click('.reader-random');assert.match(await p.$eval('.reference-picker',e=>e.textContent),/Random/);await p.click('.writing-mode-button');assert.equal(await p.$('.reader-random'),null);await p.click('.writing-mode-button');
await p.click('.setup-button');await p.click('.personal-import summary');let input=await p.$('input[type=file]');await input.uploadFile('public/data/import-example.json');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('Local'));assert.match(await p.$eval('.verse.active p',e=>e.textContent),/For God so loved/);await p.reload({waitUntil:'networkidle0'});await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('Local'));
await fs.writeFile('qa/invalid-import.json','{"books":[]}');await p.click('.setup-button');await p.click('.personal-import summary');input=await p.$('input[type=file]');await input.uploadFile('qa/invalid-import.json');await p.waitForSelector('.personal-import [role=alert]');assert.match(await p.$eval('.verse.active p',e=>e.textContent),/For God so loved/);await p.click('[aria-label="Close settings"]');await open();await p.select('[name="navigator-translation"]','DRA');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('DRA'));await p.evaluate(()=>navigator.serviceWorker.ready);await wait();await p.setOfflineMode(true);await p.reload({waitUntil:'networkidle0'});await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('DRA'));
console.log('PASS: book→chapter direct navigation; browsing preserves position; 73 Catholic books appear once; Catholic Psalm numbering; mobile 44px chapters; random hidden in focus; private JSON import/reload/rejection; Catholic offline reload.')
}finally {await b.close()}
