import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
try{const p=await b.newPage();await p.setViewport({width:1440,height:900});await p.goto(process.env.QA_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle0'});await p.waitForSelector('.verse.active');const results=[];
for(const theme of ['paper','gray','sage','night']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);const contrasts=await p.evaluate(()=>{
 const root=getComputedStyle(document.documentElement),val=n=>root.getPropertyValue(n).trim();const canvas=document.createElement('canvas');canvas.width=canvas.height=1;const ctx=canvas.getContext('2d');const rgb=c=>{ctx.clearRect(0,0,1,1);ctx.fillStyle=c;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3)};const lum=c=>rgb(c).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4}).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);const ratio=(a,b)=>{const x=lum(a),y=lum(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05)};return {text:ratio(val('--ink'),val('--page')),accent:ratio(val('--accent'),val('--page')),buttonLight:ratio(val('--page'),`color-mix(in srgb,${val('--accent')} 94%,white)`),buttonDark:ratio(val('--page'),`color-mix(in srgb,${val('--accent')} 94%,black)`)}});
 assert.ok(Object.values(contrasts).every(x=>x>=4.5),JSON.stringify({theme,contrasts}));assert.equal(await p.$eval('.scripture-wrap',e=>getComputedStyle(e).backgroundImage),'none');await p.screenshot({path:`qa/material-${theme}-reader.png`});await p.click('.reference-picker');await new Promise(r=>setTimeout(r,350));assert.match(await p.$eval('.book-cover',e=>getComputedStyle(e).backgroundImage),/data:image\/svg/);await p.screenshot({path:`qa/material-${theme}-books.png`});await p.keyboard.press('Escape');results.push({theme,contrasts});}
assert.equal(results.length,4);await fs.writeFile('qa/material-contrast.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results));console.log('PASS: four palettes, accent/body/filled-button contrast >=4.5:1 at both gradient endpoints; texture confined to book covers; Scripture surface untextured.')
}finally{await b.close()}
