import puppeteer from 'puppeteer-core'
import assert from 'node:assert/strict'
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
try {
 const p=await b.newPage();await p.setViewport({width:1440,height:900});await p.goto(process.env.QA_URL||'http://127.0.0.1:4173/',{waitUntil:'networkidle0'});await p.waitForSelector('.reference-picker');await p.click('.writing-mode-button');await p.click('.reference-picker');await p.waitForSelector('[name="reference"]');await p.type('[name="reference"]','John 3:16');await p.keyboard.press('Enter');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('John 3:16'));assert.ok(await p.$('.focus-writing'));
 await p.click('.reference-picker');await p.select('[name="navigator-translation"]','BSB');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('BSB'));await new Promise(r=>setTimeout(r,250));assert.ok(await p.$('.focus-writing'));assert.ok(await p.evaluate(()=>!!document.fullscreenElement));
 await p.click('.reference-picker');await p.keyboard.press('Escape');assert.ok(await p.$('.focus-writing'));assert.equal(await p.$('[role="dialog"]'),null);await p.click('.verse.active');await p.keyboard.press('ArrowRight');await p.waitForFunction(()=>document.querySelector('.reference-picker')?.textContent.includes('3:17'));
 await p.setViewport({width:390,height:844});await p.click('.reference-picker');await p.waitForSelector('[name="navigator-translation"]');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'qa/reference-picker-mobile.png'});console.log('PASS: focus reference click, passage selection, translation selection, fullscreen retained, Escape dismisses picker only, arrow navigation resumes, mobile picker usable.')
} catch(e) {const p=(await b.pages()).at(-1);await p.screenshot({path:'qa/picker-failure.png'});console.log(await p.$eval('.reference-picker',e=>({rect:e.getBoundingClientRect().toJSON(),html:e.outerHTML})));throw e} finally {await b.close()}
